<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TYSS-TR-0021" ignored="0" name="Default test(failed)(failed)" tests="2" failures="2" timestamp="05 Jan 2019 08:12:25 GMT" time="0.003" errors="0">
  <testcase name="fail_TC1" time="0.002" classname="TestNGExecution.DemoFail">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNGExecution.DemoFail.fail_TC1(DemoFail.java:19)
at TestNGExecution.AutomaticRunTestNG.run(AutomaticRunTestNG.java:17)
... Removed 49 stack frames]]>
    </failure>
  </testcase> <!-- fail_TC1 -->
  <testcase name="fail_TC" time="0.0" classname="TestNGExecution.DemoFail">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNGExecution.DemoFail.fail_TC(DemoFail.java:12)
at TestNGExecution.AutomaticRunTestNG.run(AutomaticRunTestNG.java:17)
... Removed 49 stack frames]]>
    </failure>
  </testcase> <!-- fail_TC -->
</testsuite> <!-- Default test(failed)(failed) -->
